FROM archlinux:latest

RUN pacman -Syu --noconfirm

RUN pacman -S --verbose --noconfirm \
        cmake \
        make \
        gcc \
        git \
        muparser \
        qt6-base \
        qt6-svg \
        python 

COPY . /src
WORKDIR /build
RUN rm -rf * && cmake -DCMAKE_INSTALL_PREFIX=/usr /src && make -j $(nproc)
