FROM ubuntu:22.04

RUN export DEBIAN_FRONTEND=noninteractive \
 && apt-get -qq update \
 && apt-get -qq upgrade \
 && apt-get install --no-install-recommends -y \
        cmake \
        make \
        g++ \
        libmuparser-dev \
        libqalculate-dev \
        libqt6svg6-dev \
        python3-dev \
        qt6-base-dev \
        libqt6widgets6 \
        libqt6gui6 \
        libqt6statemachine6 \
        libgl1-mesa-dev \
        libglvnd-dev \ 
        doctest-dev \
        git 

COPY . /src
WORKDIR /build
RUN rm -rf * && cmake -DBUILD_PYTHON=OFF /src && make -j $(nproc)
