
var settableProperties = [
    "background_color",
    "foreground_color",
    "highlight_color",
    "inputline_color",
    "border_color",
    "input_fontsize",
    "item_title_fontsize",
    "item_description_fontsize",
    "icon_size",
    "max_items",
    "space",
    "settingsbutton_size",
    "window_width"
];

var presets = {
    "Bright": {
        "input_fontsize": 36,
        "item_title_fontsize": 26,
        "item_description_fontsize": 12,
        "icon_size": 48,
        "max_items": 5,
        "space": 6,
        "settingsbutton_size": 15,
        "window_width": 640,
        "background_color": "#FFFFFF",
        "foreground_color": "#808080",
        "inputline_color": "#D0D0D0",
        "highlight_color": "#404040",
        "border_color": "#80808080"
    },
    "BrightOrange": {
        "input_fontsize": 36,
        "item_title_fontsize": 26,
        "item_description_fontsize": 12,
        "icon_size": 48,
        "max_items": 5,
        "space": 6,
        "settingsbutton_size": 15,
        "window_width": 640,
        "background_color": "#FFFFFF",
        "foreground_color": "#808080",
        "inputline_color": "#D0D0D0",
        "highlight_color": "#E07000",
        "border_color": "#80FF8000"
    },
    "BrightMagenta": {
        "input_fontsize": 36,
        "item_title_fontsize": 26,
        "item_description_fontsize": 12,
        "icon_size": 48,
        "max_items": 5,
        "space": 6,
        "settingsbutton_size": 15,
        "window_width": 640,
        "background_color": "#FFFFFF",
        "foreground_color": "#808080",
        "inputline_color": "#D0D0D0",
        "highlight_color": "#E00070",
        "border_color": "#80FF0080"
    },
    "BrightMint": {
        "input_fontsize": 36,
        "item_title_fontsize": 26,
        "item_description_fontsize": 12,
        "icon_size": 48,
        "max_items": 5,
        "space": 6,
        "settingsbutton_size": 15,
        "window_width": 640,
        "background_color": "#FFFFFF",
        "foreground_color": "#808080",
        "inputline_color": "#D0D0D0",
        "highlight_color": "#00c060",
        "border_color": "#8000FF80"
    },
    "BrightGreen": {
        "input_fontsize": 36,
        "item_title_fontsize": 26,
        "item_description_fontsize": 12,
        "icon_size": 48,
        "max_items": 5,
        "space": 6,
        "settingsbutton_size": 15,
        "window_width": 640,
        "background_color": "#FFFFFF",
        "foreground_color": "#808080",
        "inputline_color": "#D0D0D0",
        "highlight_color": "#60c000",
        "border_color": "#8080FF00"
    },
    "BrightBlue": {
        "input_fontsize": 36,
        "item_title_fontsize": 26,
        "item_description_fontsize": 12,
        "icon_size": 48,
        "max_items": 5,
        "space": 6,
        "settingsbutton_size": 15,
        "window_width": 640,
        "background_color": "#FFFFFF",
        "foreground_color": "#808080",
        "inputline_color": "#D0D0D0",
        "highlight_color": "#80c0ff",
        "border_color": "#800080FF"
    },
    "BrightViolet": {
        "input_fontsize": 36,
        "item_title_fontsize": 26,
        "item_description_fontsize": 12,
        "icon_size": 48,
        "max_items": 5,
        "space": 6,
        "settingsbutton_size": 15,
        "window_width": 640,
        "background_color": "#FFFFFF",
        "foreground_color": "#808080",
        "inputline_color": "#D0D0D0",
        "highlight_color": "#C080FF",
        "border_color": "#808000FF"
    },
    "Dark": {
        "input_fontsize": 36,
        "item_title_fontsize": 26,
        "item_description_fontsize": 12,
        "icon_size": 48,
        "max_items": 5,
        "space": 6,
        "settingsbutton_size": 15,
        "window_width": 640,
        "background_color": "#404040",
        "foreground_color": "#808080",
        "inputline_color": "#202020",
        "highlight_color": "#E0E0E0",
        "border_color": "#80808080"
    },
    "DarkOrange": {
        "input_fontsize": 36,
        "item_title_fontsize": 26,
        "item_description_fontsize": 12,
        "icon_size": 48,
        "max_items": 5,
        "space": 6,
        "settingsbutton_size": 15,
        "window_width": 640,
        "background_color": "#404040",
        "foreground_color": "#808080",
        "inputline_color": "#202020",
        "highlight_color": "#FF9020",
        "border_color": "#80FF8000"
    },
    "DarkMagenta": {
        "input_fontsize": 36,
        "item_title_fontsize": 26,
        "item_description_fontsize": 12,
        "icon_size": 48,
        "max_items": 5,
        "space": 6,
        "settingsbutton_size": 15,
        "window_width": 640,
        "background_color": "#404040",
        "foreground_color": "#808080",
        "inputline_color": "#202020",
        "highlight_color": "#FF2090",
        "border_color": "#80FF0080"
    },
    "DarkMint": {
        "input_fontsize": 36,
        "item_title_fontsize": 26,
        "item_description_fontsize": 12,
        "icon_size": 48,
        "max_items": 5,
        "space": 6,
        "settingsbutton_size": 15,
        "window_width": 640,
        "background_color": "#404040",
        "foreground_color": "#808080",
        "inputline_color": "#202020",
        "highlight_color": "#20FF90",
        "border_color": "#8000FF80"
    },
    "DarkGreen": {
        "input_fontsize": 36,
        "item_title_fontsize": 26,
        "item_description_fontsize": 12,
        "icon_size": 48,
        "max_items": 5,
        "space": 6,
        "settingsbutton_size": 15,
        "window_width": 640,
        "background_color": "#404040",
        "foreground_color": "#808080",
        "inputline_color": "#202020",
        "highlight_color": "#90FF20",
        "border_color": "#8080FF00"
    },
    "DarkBlue": {
        "input_fontsize": 36,
        "item_title_fontsize": 26,
        "item_description_fontsize": 12,
        "icon_size": 48,
        "max_items": 5,
        "space": 6,
        "settingsbutton_size": 15,
        "window_width": 640,
        "background_color": "#404040",
        "foreground_color": "#808080",
        "inputline_color": "#202020",
        "highlight_color": "#2090FF",
        "border_color": "#800080FF"
    },
    "DarkViolet": {
        "input_fontsize": 36,
        "item_title_fontsize": 26,
        "item_description_fontsize": 12,
        "icon_size": 48,
        "max_items": 5,
        "space": 6,
        "settingsbutton_size": 15,
        "window_width": 640,
        "background_color": "#404040",
        "foreground_color": "#808080",
        "inputline_color": "#202020",
        "highlight_color": "#A040FF",
        "border_color": "#808000FF"
    }
}

