// Copyright (c) 2022 Manuel Schneider

#pragma once
#include "albert/albert.h"
#include "albert/config.h"
#include "albert/export.h"
#include "albert/extension.h"
#include "albert/extensionregistry.h"
#include "albert/extensions/configwidgetprovider.h"
#include "albert/extensions/frontend.h"
#include "albert/extensions/globalqueryhandler.h"
#include "albert/extensions/indexqueryhandler.h"
#include "albert/extensions/pluginprovider.h"
#include "albert/extensions/queryhandler.h"
#include "albert/logging.h"
#include "albert/plugin.h"
#include "albert/util/extensionwatcher.h"
#include "albert/util/backgroundexecutor.h"
#include "albert/util/timeprinter.hpp"
#include "albert/util/history.h"
#include "albert/util/standarditem.h"
#include "albert/util/util.h"
