// Copyright (c) 2022 Manuel Schneider

#pragma once
#include "albert/albert.h"
#include "albert/config.h"
#include "albert/configwidgetprovider.h"
#include "albert/export.h"
#include "albert/extension.h"
#include "albert/extensionregistry.h"
#include "albert/extensionwatcher.h"
#include "albert/frontend.h"
#include "albert/globalqueryhandler.h"
#include "albert/history.h"
#include "albert/indexqueryhandler.h"
#include "albert/item.h"
#include "albert/logging.h"
#include "albert/plugin.h"
#include "albert/pluginprovider.h"
#include "albert/query.h"
#include "albert/queryhandler.h"
#include "albert/standarditem.h"
